eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
microservice:
   order-service:
     endpoint:
       uri: http://OrderApplication/order/initiatePayment
   payment-service:
     endpoint:
       uri:  http://PaymentApplication/payment/initiatePayment
